export const GAS_CONSTANTS = {
  STANDARD_TRANSFER_GAS: BigInt(21000),
  ERC20_TRANSFER_GAS: BigInt(65000),
  BUFFER_PERCENT: BigInt(3),
  MINIMUM_BUFFER_NATIVE_TOKEN: "0.0001",
  FALLBACK_RESERVE_NATIVE_TOKEN: "0.001",
  NATIVE_TOKEN_DECIMALS: 18,
} as const;

export const BIGINT_ZERO = BigInt(0);

export const PERCENTAGE_OPTIONS = [25, 50, 75, 100] as const;
